version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass123'
      POSTGRES_DB: 'apivendas'

  redis:
    image: redis
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/var/lib/redisinsight/db

volumes:
  database:
  redisinsight:
